#!/usr/bin/env bash
# Display information about subdomains

domain="$1"
sub="$2"
subdomains=("www" "lb-01" "web-01" "web-02")

digging() {
    # dig command
    sub="$2"
    INFO="$(dig "$sub.$domain" | grep -A1 'ANSWER SECTION:' | awk 'NR==2')"
    IP=$(echo "$INFO" | awk '{print $5}')
    RECORD=$(echo "$INFO" | awk '{print $4}')
    echo -e "The subdomain $sub is a $RECORD record and points to $IP"
}

if [ $# -eq 1 ]; then
    for subs in "${subdomains[@]}"; do
        digging "$domain" "$subs"
    done
elif [ $# -eq 2 ]; then
    digging "$domain" "$sub"
fi
