#!/usr/bin/env bash
# Install nginx on web-01 listenting to port 80
echo -e "Update and install Nginx\n"
sudo apt-get update -y -qq && sudo apt-get install nginx -y

echo -e "\nStart nginx service and all firewall\n"
sudo servivce nginx start
sudo ufw allow 'Nginx HTTP'

echo -e "\nset the user ownership to website files\n"
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backupu default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Restarting nginx
sudo service nginx restart

echo -e "\nCompleted."
