#!/usr/bin/env bash
# Configuring web-02 to be identical to web-01
sudo apt-get update -y -qq && sudo apt-get install nginx -y

sudo service nginx start
sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html
echo Ceci n\'est pas une page > /var/www/html/custom_404.html

# Configuring redirection
sudo sed -i '/^\sserver_name.*/a \        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Custom error page
sudo sed -i '/^\slocation.*/i \        error_page 404 /error_404.html;' /etc/nginx/sites-available/default

# Configuring response header
sudo sed -i '/^\slocation.*/i \        add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

# Running the server
sudo service nginx start
