#!/usr/bin/env bash
# Installs haproxy

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" > /etc/default/haproxy

echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 522879-web-01 54.84.48.73:80 check
   server 522879-web-02 54.197.73.171:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy restart
