#!/usr/bin/env bash
# Installs haproxy

sudo apt-get -y update
sudo apt-get install -y haproxy

echo "
   bind *:80
   mode http
   balance roundrobin
   server 522879-web-01 54.84.48.73:80 check
   server 522879-web-02 54.197.73.171:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo haproxy -c -f /etc/haproxy/haproxy.cfg

sudo service haproxy restart
