#!/usr/bin/env bash
# Remove the default enabled sites
# Then configure it again to liten on port 80
# Finally restart nginx service

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
