#!/usr/bin/env bash
# This script displays "I am alive" to the file /tmp/my_process
# In between each iteration of the loop, the program should pause for 2 seconds

while true
do
	echo "I am alive!" >> /tmp/my_process
	sleep 2
done
