#!/usr/bin/env bash
# This script display numbers from 1 to 100
# displays FizzBuzz when the number is multiple of 3 and 5
# displays Fizz when the number is multiple of 3
# displays Buzz when the number is multiple of 5
# otherwise, displays the number
# in a list format

for x in {1..100}
do
	if (( x % 3 == 0 && x % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( x % 5 == 0 ))
	then
		echo "Buzz"
	elif (( x % 3 == 0))
	then
		echo "Fizz"
	else
		echo "$x"
	fi
done
