#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd using while + IFS
# format: "The user USERNAME is part of the GROUP_ID gang, lives in HOME_DIRECTORY and rides COMMAND/SHELL. USER ID's place is protected by the passcode PASSWORD, more info about the user here: USER ID INFO"

while IFS=":" read -r USERNAME PASSWORD USER_ID GROUP_ID INFO HOME_DIRECTORY SHELL;
do
	echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $SHELL. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $INFO"
done < "/etc/passwd"
