#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code and displays its data
# format: OCCURENCE_NUMBER IP HTTP_CODE
# in list format
# ordered from the greatest to lowest number of occurences

awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -nr
