#!/usr/bin/env bash
# createse an RSA key pair:
# - name of the created private key must be school
# - number of bits in the key 4096
# - protected by passphrase betty
ssh-keygen -f school -b 4096 -P betty
